In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import datetime as dt
import numpy as np
from tqdm import tqdm
from sklearn.metrics import accuracy_score

In [2]:
df = pd.read_csv('pe_dataset.csv')
df.drop(['Unnamed: 0', 'year'], inplace=True, axis=1)
df['Hora'] = [dt.datetime.time(d) for d in pd.to_datetime(df['data'])]
df['Hora_float'] = [t.hour+t.minute/60.0 for t in df['Hora']]

df['dia'] = [int(str(d)[8:10]) for d in pd.to_datetime(df['data'])]

df_232 = df[df['br']==232]
df_104 = df[df['br']==104]

df_232.head(20)

C:\Users\Hugo\AppData\Local\Programs\Python\Python37\lib\site-packages\IPython\core\interactiveshell.py:3051: DtypeWarning: Columns (26,27,28) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)


data dia_semana  uf   br     km               municipio  \
0   2007-01-01 06:30:00    segunda  PE  232  327.0                CUSTODIA   
2   2007-01-01 14:20:00    segunda  PE  232  232.2               PESQUEIRA   
4   2007-01-01 17:30:00    segunda  PE  232  118.2                 CARUARU   
8   2007-01-02 12:50:00      terça  PE  232   54.7                 GRAVATA   
10  2007-01-02 16:00:00      terça  PE  232   18.0                  MORENO   
13  2007-01-03 08:40:00     quarta  PE  232  412.5           SERRA TALHADA   
19  2007-01-03 14:10:00     quarta  PE  232  254.7               ARCOVERDE   
22  2007-01-03 07:00:00     quarta  PE  232  185.4             BELO JARDIM   
25  2007-01-04 08:50:00     quinta  PE  232   95.2                BEZERROS   
26  2007-01-04 10:30:00     quinta  PE  232  132.5                 CARUARU   
33  2007-01-01 17:20:00    segunda  PE  232  100.1                BEZERROS   
36  2007-01-05 06:30:00      sexta  PE  232   24.9                  MORENO   
38  2007-01-05 12:50:00      sexta  PE  232   64.0                  POMBOS   
47  2007-01-06 12:30:00     sábado  PE  232  277.7                SERTANIA   
52  2007-01-03 09:30:00     quarta  PE  232   85.5                 GRAVATA   
62  2007-01-08 10:50:00    segunda  PE  232    8.0                  RECIFE   
63  2007-01-07 22:00:00    domingo  PE  232  387.0                 CALUMBI   
66  2007-01-01 15:30:00    segunda  PE  232  180.0             BELO JARDIM   
77  2007-01-09 04:00:00      terça  PE  232  517.7               SALGUEIRO   
78  2007-01-09 12:05:00      terça  PE  232   45.6  VITORIA DE SANTO ANTAO   

                 causa_acidente        tipo_acidente classificacao_acidente  \
0                      dormindo          capotamento    com vítimas feridas   
2                      dormindo          capotamento            sem vítimas   
4                        outras      colisão lateral            sem vítimas   
8                defeito na via           tombamento            sem vítimas   
10                       outras       saída de pista            sem vítimas   
13  defeito mecânico em veículo      colisão lateral            sem vítimas   
19           ingestão de álcool  colisão transversal            sem vítimas   
22             falta de atenção     colisão traseira            sem vítimas   
25             falta de atenção          capotamento    com vítimas feridas   
26             falta de atenção      colisão lateral            sem vítimas   
33             animais na pista          capotamento    com vítimas feridas   
36      velocidade incompatível       saída de pista            sem vítimas   
38             falta de atenção     colisão traseira            sem vítimas   
47             falta de atenção     colisão traseira            sem vítimas   
52             falta de atenção     colisão traseira            sem vítimas   
62             falta de atenção  colisão transversal    com vítimas feridas   
63  defeito mecânico em veículo           tombamento            sem vítimas   
66             falta de atenção     colisão traseira    com vítimas feridas   
77                     dormindo       saída de pista    com vítimas feridas   
78                       outras       saída de pista            sem vítimas   

       fase_dia  ...  uop yearmonthdate     km_bins   periodo      feriado  \
0     pleno_dia  ...  NaN    2007-01-01  [325, 330)    [4, 8)      feriado   
2     pleno_dia  ...  NaN    2007-01-01  [230, 235)  [12, 16)      feriado   
4     pleno_dia  ...  NaN    2007-01-01  [115, 120)  [16, 20)      feriado   
8     pleno_dia  ...  NaN    2007-01-02    [50, 55)  [12, 16)  pos-feriado   
10    pleno_dia  ...  NaN    2007-01-02    [15, 20)  [16, 20)  pos-feriado   
13    pleno_dia  ...  NaN    2007-01-03  [410, 415)   [8, 12)  not-feriado   
19    pleno_dia  ...  NaN    2007-01-03  [250, 255)  [12, 16)  not-feriado   
22  plena_noite  ...  NaN    2007-01-03  [185, 190)    [4, 8)  not-feriado   
25    pleno_dia  .

In [3]:
df_104.sort_values(by="data", inplace=True)
df_104.head(50)

C:\Users\Hugo\AppData\Local\Programs\Python\Python37\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.


data dia_semana  uf   br     km              municipio  \
27    2007-01-01 17:40:00    segunda  PE  104   76.3                CARUARU   
5     2007-01-02 07:40:00      terça  PE  104   74.1                CARUARU   
14    2007-01-02 10:00:00      terça  PE  104  127.5                PANELAS   
56    2007-01-05 21:40:00      sexta  PE  104   59.5                CARUARU   
178   2007-01-07 18:30:00    domingo  PE  104   20.0  TAQUARITINGA DO NORTE   
147   2007-01-09 09:20:00      terça  PE  104   49.4                CARUARU   
105   2007-01-09 13:00:00      terça  PE  104   67.5                CARUARU   
83    2007-01-09 15:00:00      terça  PE  104  128.2                PANELAS   
89    2007-01-10 08:15:00     quarta  PE  104   32.1                CARUARU   
107   2007-01-12 13:35:00      sexta  PE  104   79.0              AGRESTINA   
108   2007-01-12 19:20:00      sexta  PE  104   73.3                CARUARU   
145   2007-01-16 12:30:00      terça  PE  104   25.2               TORITAMA   
149   2007-01-16 17:30:00      terça  PE  104   30.6               TORITAMA   
228   2007-01-19 03:00:00      sexta  PE  104   61.3                CARUARU   
194   2007-01-20 16:30:00     sábado  PE  104   54.8                CARUARU   
199   2007-01-21 02:20:00    domingo  PE  104   12.3  TAQUARITINGA DO NORTE   
222   2007-01-21 17:30:00    domingo  PE  104   72.0                CARUARU   
229   2007-01-22 18:10:00    segunda  PE  104   66.1                CARUARU   
244   2007-01-22 19:30:00    segunda  PE  104   61.9                CARUARU   
246   2007-01-24 14:30:00     quarta  PE  104   66.7                CARUARU   
252   2007-01-24 18:00:00     quarta  PE  104   67.2                CARUARU   
309   2007-01-25 12:00:00     quinta  PE  104   63.5                CARUARU   
265   2007-01-26 07:25:00      sexta  PE  104   47.6                CARUARU   
280   2007-01-26 17:50:00      sexta  PE  104   85.5              AGRESTINA   
290   2007-01-27 22:15:00     sábado  PE  104   58.0                CARUARU   
299   2007-01-28 17:20:00    domingo  PE  104   38.7                CARUARU   
328   2007-01-29 08:20:00    segunda  PE  104   63.8                CARUARU   
327   2007-01-29 18:15:00    segunda  PE  104   52.0                CARUARU   
3467  2007-02-01 14:20:00     quinta  PE  104   65.4                CARUARU   
385   2007-02-01 18:20:00     quinta  PE  104  104.7              AGRESTINA   
509   2007-02-02 16:50:00      sexta  PE  104   63.8                CARUARU   
368   2007-02-04 18:00:00    domingo  PE  104   63.6                CARUARU   
374   2007-02-05 12:45:00    segunda  PE  104   65.5                CARUARU   
1470  2007-02-06 07:35:00      terça  PE  104   67.5                CARUARU   
398   2007-02-06 12:40:00      terça  PE  104   66.7                CARUARU   
410   2007-02-07 04:10:00     quarta  PE  104   68.3                CARUARU   
4729  2007-02-09 13:45:00      sexta  PE  104   64.5                CARUARU   
510   2007-02-14 12:30:00     quarta  PE  104   23.2  TAQUARITINGA DO NORTE   
1860  2007-02-14 14:00:00     quarta  PE  104  101.0                 CUPIRA   
482   2007-02-14 15:55:00     quarta  PE  104   34.9                CARUARU   
491   2007-02-15 09:20:00     quinta  PE  104   30.0               TORITAMA   
493   2007-02-15 15:25:00     quinta  PE  104   33.4                CARUARU   
506   2007-02-16 09:00:00      sexta  PE  104   24.0               TORITAMA   
514   2007-02-16 13:00:00      sexta  PE  104   30.0               TORITAMA   
525   2007-02-17 06:00:00     sábado  PE  104   72.2                CARUARU   
598   2007-02-17 07:00:00     sábado  PE  104  100.8                 CUPIRA   
591   2007-02-21 19:30:00     quarta  PE  104   38.8                CARUARU   
602   2007-02-23 11:30:00      sexta  PE  104   78.0              AGRESTINA   
653   2007-02-26 13:20:00    segunda  PE  104  120.5                PANELAS   
667   2007-02-27 02:20:00      terça  PE  104  119.4                PAN

# Em diante to fazendo só para a br_104

## Parada vai ser o seguinte.

### Gerar uma função linear qualquer com o que seria o score de risco do acidente.

100\*mortos + 20\*feridos_graves + 5\*feridos_leves + 1\*ilesos + 0\*ignorados

### Depois disso eu vou observar um treshold para esse score de forma que eu possa binarizar a parada entre: Vale a pena ir uma viatura e não vale.

In [4]:
df_104['Score'] = 125*df_104['mortos']+25*df_104['feridos_graves']+5*df_104['feridos_leves']+1*df_104['ilesos']

C:\Users\Hugo\AppData\Local\Programs\Python\Python37\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.


# Para fazer o markov eu vou ter que agrupar por semana

## Juntando observações

In [5]:
from datetime import date

df_104.data = pd.to_datetime(df_104.data, yearfirst=True, errors='ignore')

data_max = df_104.data.max()
data_min = df_104.data.min()

km_bin_size = 10
dias_aglomerados = 60

meses = (data_max - data_min).days//dias_aglomerados+2
km_bins = int((df_104.km.max() - df_104.km.min())/km_bin_size)+2
print(meses, km_bins)

matriz_dados = np.zeros((meses,km_bins))
matriz_feriados = np.zeros((meses,km_bins))

81 16


C:\Users\Hugo\AppData\Local\Programs\Python\Python37\lib\site-packages\pandas\core\generic.py:5302: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self[name] = value


In [6]:
data_start=data_min

for i in tqdm(range(matriz_dados.shape[0])):
    
    data_fim = dt.timedelta(days=dias_aglomerados) + data_start 
    km_start=0
    
    for j in range(matriz_dados.shape[1]):
        
        km_fim=km_start+km_bin_size
        
        sum_score = df_104[(df_104.km>= km_start) & (df_104.km< km_fim) & (df_104.data < data_fim) & (df_104.data >= data_start)]['Score'].sum()
        feriado_list = df_104[(df_104.km>= km_start) & (df_104.data <= data_fim) & (df_104.data>= data_start)].feriado.unique()
        
        #print(km_start, km_fim, data_start, data_fim,sum_score)
        
        if ('feriado' in feriado_list) and ('pre-feriado' in feriado_list) and ('pos-feriado' in feriado_list):
            feriado_var=1
        elif ('feriado' in feriado_list) and (('pre-feriado' in feriado_list) or ('pos-feriado' in feriado_list)):
            feriado_var=0.75
        elif ('feriado' not in feriado_list) and (('pre-feriado' in feriado_list) and ('pos-feriado' in feriado_list)):
            feriado_var=0.5
        elif ('feriado' not in feriado_list) and (('pre-feriado' in feriado_list) or ('pos-feriado' in feriado_list)):
            feriado_var=0.25
        elif ('feriado' not in feriado_list) and ('pre-feriado' not in feriado_list) and ('pos-feriado' not in feriado_list):
            feriado_var=0
            
        matriz_dados[i,j]=sum_score
        matriz_feriados[i,j]=feriado_var 
        
        km_start+=km_bin_size
        
    data_start=data_fim

100%|██████████| 81/81 [00:04<00:00, 20.08it/s]


In [7]:
np.save('matriz_dados_br_104.npy', matriz_dados)
np.save('matriz_feriados.npy', matriz_feriados)

In [8]:
# se quiser dar load e não esperar 1 minutor...
matriz_dados= np.load('matriz_dados_br_104.npy')
matriz_feriados=np.load('matriz_feriados.npy')

In [9]:
threshold = 50
print(matriz_dados[matriz_dados>threshold].shape)
print(matriz_dados[matriz_dados<=threshold].shape)

(501,)
(795,)


In [10]:
matriz_dados_bool = np.where(matriz_dados>threshold, 1, 0)

print(matriz_dados_bool[matriz_dados_bool==1].shape)
print(matriz_dados_bool[matriz_dados_bool==0].shape)

(501,)
(795,)


In [11]:
def get_sum_consec_1(ndarray):
    count = 0
    for i in np.arange(1,ndarray.shape[0]):
        if ndarray[i]!=0 and ndarray[i-1]!=0:
            count+=1
    return count

def get_sum_consec_0(ndarray):
    count = 0
    for i in np.arange(1,ndarray.shape[0]):
        if ndarray[i]==0 and ndarray[i-1]==0:
            count+=1
    return count

def get_rank_value(serie_principal, serie_pesos, mes_target, verbose=False):
        
    # semana_target é a próxima semana!
    
    # Peso vai ser caculado pela correlação entre os feriados e as morte 
    # versus a distância entre a probabildiade original e 1.
    # O peso é adicionado a probabilidade original até a semana atual e anterior
    
    # Probabilidade de Morte até a semana atual
    PA_M = serie_principal[0:mes_target].sum()/(mes_target-1 + 0.001)
    D_PA_M = 1 - PA_M
    Peso_PA_M = np.sqrt(D_PA_M*np.abs(np.nan_to_num(np.corrcoef(serie_principal[0:mes_target], serie_pesos[0:mes_target])[0,1])))
    PA_M += Peso_PA_M
    
    # Probabilidade de Morte até a semana anterior
    PB_M = serie_principal[0:mes_target-1].sum()/(mes_target-2 + 0.001)
    D_PB_M = 1 - PB_M
    Peso_PB_M = np.sqrt(D_PB_M*np.abs(np.nan_to_num(np.corrcoef(serie_principal[0:mes_target-1], serie_pesos[0:mes_target-1])[0,1])))
    PB_M += Peso_PB_M
    
    # Probabilidade de ter Morte na Semana anterior, dado que teve na semana atual
    PBA_M = get_sum_consec_1(serie[0:mes_target-1])/((mes_target-2)*PB_M + 0.001) 
    
    # Probabilidade de ter Morte na semana atual, dado que teve morte na semana anterior
    PAB_M = (PBA_M*PA_M)/(PB_M + 0.001)
    
    #ANALOGAMENTE
    
    # Probabilidade de não ter morte até a semana atual
    PA_NM= 1-PA_M
    
    # Probabilidade de não ter morte até a semana anterior
    PB_NM = 1-PB_M
    
    # Probabilidade de não ter Morte na Semana anterior, dado que teve na semana atual
    PBA_NM = get_sum_consec_0(serie[0:mes_target-1])/((mes_target-2)*PB_NM+ 0.001) 
    
    # Probabilidade de não ter Morte na semana atual, dado que teve morte na semana anterior
    PAB_NM = (PBA_NM*PA_NM)/(PB_NM + 0.001)
    
    # Matriz de transição de estados A
    A = np.array([[PAB_M, 1-PAB_M], [1-PAB_NM, PAB_NM]])
    
    # Matriz para o próximo estado: previsão
    A_K = A.dot(A)
    
    # Valor do Rank é a probabilidade de ter morte, dado que não houve morte mais dado que houve morte anteriormente
    rank_value_K = (A_K[0,0]*PA_M) + (A_K[1,0]*PA_NM)
    
    debug_list = [PA_M, PA_NM, PB_M, PB_NM, PAB_M, PAB_NM, PBA_M, PBA_NM, A]
    
    return rank_value_K, debug_list

In [12]:
matriz_proba = np.zeros((matriz_dados_bool.shape[0],matriz_dados_bool.shape[1]))
months_to_look = 12*2
debug = []
for km_bin in tqdm(range(matriz_proba.shape[1])):
    for month in range(matriz_proba.shape[0]):
        month_i = month - months_to_look
        if month_i<1:
            month_i = 0
        if month > 2:    
            serie = matriz_dados_bool[month_i:month-1, km_bin]
            serie_pesos = matriz_feriados[month_i:month-1, km_bin]

            matriz_proba[month, km_bin], debug_list = get_rank_value(serie, serie_pesos, month)
            debug.append(debug_list)
            
matriz_proba=np.nan_to_num(matriz_proba)
matriz_proba

  0%|          | 0/16 [00:00<?, ?it/s]C:\Users\Hugo\AppData\Local\Programs\Python\Python37\lib\site-packages\numpy\lib\function_base.py:2534: RuntimeWarning: invalid value encountered in true_divide
  c /= stddev[:, None]
C:\Users\Hugo\AppData\Local\Programs\Python\Python37\lib\site-packages\numpy\lib\function_base.py:2535: RuntimeWarning: invalid value encountered in true_divide
  c /= stddev[None, :]
100%|██████████| 16/16 [00:00<00:00, 33.00it/s]


array([[ 0.        ,  0.        ,  0.        , ...,  0.        ,
         0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        , ...,  0.        ,
         0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        , ...,  0.        ,
         0.        ,  0.        ],
       ...,
       [ 0.20555522,  0.48291367,  0.55064692, ...,  0.38591163,
        -0.57853229,  0.20555522],
       [ 0.20395763,  0.47862854,  0.55227639, ...,  0.38593747,
        -0.55313774,  0.20395763],
       [ 0.20237388,  0.48456146,  0.51803646, ...,  0.3842934 ,
        -0.52859226,  0.20237388]])

In [13]:
debug

[[0.0,
  1.0,
  0.0,
  1.0,
  0.0,
  0.9980029960049943,
  0.0,
  0.9990009990009991,
  array([[0.      , 1.      ],
         [0.001997, 0.998003]])],
 [0.0,
  1.0,
  0.0,
  1.0,
  0.0,
  0.9985017481269356,
  0.0,
  0.9995002498750625,
  array([[0.        , 1.        ],
         [0.00149825, 0.99850175]])],
 [0.0,
  1.0,
  0.0,
  1.0,
  0.0,
  0.9986681096311221,
  0.0,
  0.9996667777407531,
  array([[0.        , 1.        ],
         [0.00133189, 0.99866811]])],
 [0.0,
  1.0,
  0.0,
  1.0,
  0.0,
  0.9987513111732057,
  0.0,
  0.9997500624843788,
  array([[0.        , 1.        ],
         [0.00124869, 0.99875131]])],
 [0.5748939869292691,
  0.4251060130707309,
  0.5999700058738533,
  0.4000299941261467,
  0.0,
  2.1188526047497125,
  0.0,
  1.9988506902055212,
  array([[ 0.       ,  1.       ],
         [-1.1188526,  2.1188526]])],
 [0.5208057095257197,
  0.4791942904742803,
  0.5393230999808627,
  0.4606769000191373,
  0.0,
  1.5015116336282706,
  0.0,
  1.4466224872380387,
  array

# Avaliação

In [18]:
rank_size = 4
time_test = 6 # último ano

last_year_probas = matriz_proba[-time_test:,:]

week_acc = []
for month in range(time_test):
    arg_sort_week = np.argsort(last_year_probas[month, :])[-rank_size:]
    week_acc.append(matriz_dados_bool[month, arg_sort_week].sum()/rank_size)
    
print(week_acc)

[0.75, 0.75, 1.0, 0.5, 0.5, 0.5]


In [15]:
matriz_proba[-12:,:]

array([[ 3.50815593e-01,  4.01630986e-01,  5.88542098e-01,
         5.01737860e-01,  3.26879268e-01,  4.94525427e-01,
         6.55293651e-01,  6.28592139e-01,  5.83947618e-01,
         4.11699302e-01,  4.90537571e-01,  4.37646069e-01,
         3.86565183e-01,  4.25300430e-01,  2.15547748e-01,
         2.20424697e-01],
       [ 3.53270977e-01,  4.15863083e-01,  5.56387155e-01,
         5.02232976e-01,  3.11543242e-01,  4.80240108e-01,
         6.49487267e-01,  6.04586998e-01,  5.89865202e-01,
         4.11003208e-01,  4.86057288e-01,  4.42232909e-01,
         3.85758537e-01,  4.57692922e-01,  2.13609867e-01,
         2.18742274e-01],
       [ 3.42933751e-01,  4.04262286e-01,  5.50266541e-01,
         4.93670247e-01,  4.38888349e-01,  4.54581945e-01,
         6.29274507e-01,  6.09269082e-01,  5.47657445e-01,
         4.03817298e-01,  5.07822504e-01,  4.58429383e-01,
         4.16408423e-01,  4.61932275e-01,  2.11691942e-01,
         2.17064081e-01],
       [ 2.15391819e-01,  4.20385139e